const keywords = [{topic:'correlation(pearson)',keywords:['correlation','relationship','related',
														 'pearson']},
				  {topic:'central tendency',keywords:['mean','median','mode','central tendency','central',
				  									  'histogram','descriptive']},
				  {topic:'standard deviation',keywords:['variance','standard deviation','sd']},
				  {topic:'quartiles and iqr',keywords:['quartiles','q1','q2','q3','iqr','interquartile','range']},
				  {topic:'z-score',keywords:['z-score']},
				  {topic:'linear regression',keywords:['line','linear regression','least squares','fitting']},
				  {topic:'quadratic regression',keywords:['curve','parabola','quadratic regression','fitting']},
				  {topic:'normal dist.',keywords:['normal distribution','bell curve','probability']},
				  {topic:'binomial dist.',keywords:['binomial distribution']},
				  {topic:'logistic map',keywords:['fun']},
				  {topic:'collatz conj.',keywords:['collatz','3x+1','miscellaneous']},
				  {topic:'t-test(one-sample)',keywords:['t','ttest','one', 'sample']},
				  {topic:'t-test(two-sample)',keywords:['two','sample','ttest']},
				  {topic:'chi-square test',keywords:['chi','square','compare']},
				  {topic:'mann-whitney u-test',keywords:['mann','whitney','u']},
				  {topic:'multiple linear',keywords:['multiple','linear','regression']}

				   ];